Update to gdbm 1.23

diff --git a/vendor/gdbm/Makefile.am b/vendor/gdbm/Makefile.am
--- a/vendor/gdbm/Makefile.am
+++ b/vendor/gdbm/Makefile.am
@@ -1,6 +1,5 @@
 # This file is part of GDBM.                                   -*- Makefile -*-
-# Copyright (C) 2007, 2011, 2013, 2016-2017 Free Software Foundation,
-# Inc.
+# Copyright (C) 2007-2022 Free Software Foundation, Inc.
 #
 # GDBM is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -15,24 +14,34 @@
 # You should have received a copy of the GNU General Public License
 # along with GDBM. If not, see <http://www.gnu.org/licenses/>. */
 
-ACLOCAL_AMFLAGS = -I m4
-EXTRA_DIST = build-aux/config.rpath NOTE-WARNING git2chg.awk
+EXTRA_DIST = build-aux/config.rpath NOTE-WARNING
 
 if COMPAT_OPT
   MAYBE_COMPAT = compat
 endif
-if ENABLE_EXPORT
-  MAYBE_EXPORT = export
-endif
-SUBDIRS = po src doc $(MAYBE_COMPAT) $(MAYBE_EXPORT) tests
+SUBDIRS = po src tools doc $(MAYBE_COMPAT) tests
 
 AM_DISTCHECK_CONFIGURE_FLAGS = --enable-libgdbm-compat
 
-dist-hook:
+.PHONY: set-dist-date
+set-dist-date:
 	rm -f $(distdir)/src/version.c; \
 	d=`date '+%d/%m/%Y'`; \
 	sed 's|/\*@DIST_DATE@\*/|"'"$$d"'"|' $(srcdir)/src/version.c > \
 		$(distdir)/src/version.c
+
+dist-hook: ChangeLog set-dist-date
+	@if test -f ChangeLog && test -f NEWS; then			\
+	  PATCHLEV=`echo "$(PACKAGE_VERSION)" | sed -r "s/[0-9]+\.[0-9]+\.?//"`;\
+	  if test $${PATCHLEV:-0} -lt 50; then				     \
+	    if grep -q FIXME NEWS; then					     \
+	      echo >&2 "*** NEWS file contains FIXMEs";			     \
+	      echo >&2 "*** Aborting";					     \
+	      exit 1;							     \
+	    fi;								     \
+	  fi;                                                                \
+	fi
+
 
 gen_start_date = 2016-07-08
 prev_change_log = ChangeLog.cvs
@@ -40,8 +49,18 @@ prev_change_log = ChangeLog.cvs
 .PHONY: ChangeLog
 ChangeLog:
 	$(AM_V_GEN)if test -d .git; then                                    \
-                git log --pretty='format:%ct  %an  <%ae>%n%n%s%n%n%b%n'     \
-                        --since=$(gen_start_date) |                         \
-                awk -f $(top_srcdir)/git2chg.awk                            \
-                    -v append=$(top_srcdir)/$(prev_change_log) > ChangeLog; \
+          (git log --pretty='format:%ad  %cn  <%ae>%n%n%w(72,8,8)%s%n%n%b'  \
+                   --date=short                                             \
+                   --since=$(gen_start_date);                               \
+           echo "";                                                         \
+           cat $(prev_change_log);                                          \
+           echo "";                                                         \
+           echo "Local Variables:";                                         \
+           echo "mode: change-log";                                         \
+           echo "version-control: never";                                   \
+           echo "buffer-read-only: t";                                      \
+           echo "End:") > ChangeLog.tmp;                                    \
+          cmp ChangeLog ChangeLog.tmp > /dev/null 2>&1 ||                   \
+            mv ChangeLog.tmp ChangeLog;                                     \
+          rm -f ChangeLog.tmp;                                              \
         fi
